# -*- coding: utf-8 -*-
"""remote_work_ai_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UbVfvZt2qxw1MF6pgXPJKZMpwdjT3dU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.read_csv("Remote_Work_AI_2026.csv")
remote_df=pd.read_csv("Remote_Work_AI_2026.csv")

remote_df.head()

remote_df.info()

remote_df.describe()

remote_df.isnull().sum()

remote_df['AI_Tools_Used']==remote_df['AI_Tools_Used'].fillna("No Ai Tools Used", inplace=True)

remote_df.isnull().sum()

remote_df["AI_Tools_Used"].value_counts()
# Yaklaşık 3'te 1 i Ai kullanmıyor.

remote_df["Work_Location"].value_counts()

sns.countplot(x="Work_Location", data=remote_df)

plt.title("Çalışma Modeli Dağılımı")

plt.show()

sns.boxplot(
    x="Work_Location",
    y="Wellbeing_Score",
    data=remote_df
)

plt.title("Çalışma Modeli ve Wellbeing İlişkisi")

plt.show()
#Remote çalışanların refah seviyesi daha yüksek çıkmıştır.

sns.boxplot(
    x="Work_Location",
    y="Productivity_Score",
    data=remote_df
)

plt.title("Çalışma Modeli ve Verimlilik İlişkisi")

plt.show()
#Remote çalışanlar daha yüksek wellbeing,productivity gösteriyor.

remote_df["AI_Usage"] = remote_df["AI_Tools_Used"].apply(
    lambda x: "AI Kullanıyor" if x != "No Ai Tools Used" else "AI Kullanmıyor"
)
remote_df["AI_Usage"].value_counts()

sns.boxplot(
    x="AI_Usage",
    y="Productivity_Score",
    data=remote_df
)

plt.title("AI Kullanımı ve Verimlilik İlişkisi")

plt.show()
# Ai araçları kullanan çalışanların productivity skorlarının daha yüksek olduğu gözlemlenmiştir.
# Ai kullanmayan çalışanlarda daha düşük productivity değerleri görülmektedir.
# Bu durum Ai araçlarının çalışan verimliliği üzerinde olumlu etkileri olduğunu gösterir.

sns.boxplot(
    x="AI_Usage",
    y="Wellbeing_Score",
    data=remote_df
)

plt.title("AI Kullanımı ve Wellbeing İlişkisi")

plt.show()
# Ai araçları kullanan çalışanların refah skorlarının daha yüksek olduğu gözlemlenmiştir.
# Bu sonuca göre Ai araçlarının çalışan memnuniyeti ve refahına olumlu katkı sağlayabileceğini göstermektedir.

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="Commute_Time_Min",
    y="Wellbeing_Score",
    hue="Work_Location",
    data=remote_df
)

plt.title("Ulaşım Süresi ve Wellbeing İlişkisi")

plt.show()
#Genel olarak ulaşım süresi arttıkça wellbeing düşüyor özellikle On-site çalışanlarda çok belirgin.
# Özellikle remote çalışanların ulaşım sürelerinin düşük ve wellbeing seviyelerinin yüksek olduğu görülmekte.
# Bu durum ulaşım süresinin çalışan yaşam kalitesi üzerinde olumsuz etkiler oluşturabileceğini göstermektedir.

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="Weekly_Work_Hours",
    y="Wellbeing_Score",
    hue="Work_Location",
    data=remote_df
)

plt.title("Haftalık Çalışma Süresi ve Wellbeing İlişkisi")

plt.show()
# Çalışma süresi arttıkça wellbeing düşüyor. Özellikle 50+ saat çalışanlarda wellbeing ciddi şekilde azalıyor.
# Remote çalışanlar daha düşük-orta çalışma saatlerinde bile yüksek wellbeingi koruyor.Yani Remote çalışma modeli çalışan psikolojisini koruyor olabilir.
# 40 saat civarı en dengeli bölge gibi görünüyor. Yani en optimum çalışma süresi olabilir.

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="Wellbeing_Score",
    y="Productivity_Score",
    hue="Work_Location",
    data=remote_df
)

plt.title("Wellbeing ve Verimlilik İlişkisi")

plt.show()
# Wellbeing'i yüksek çalışan, daha verimli çalıştığına ulaşılmıştır. Özellikle remote çalışanların. Sırasıyla Hybrid ve On-site şeklinde Wellbeing ve verimlilik düşüyor.

numeric_df = remote_df.select_dtypes(include=np.number)

plt.figure(figsize=(8,6))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Korelasyon Haritası")

plt.show()
#Korelasyon analizi sonucunda wellbeing ve productivity skorları arasında güçlü pozitif ilişki var analiz ettiğimiz gibi.
# Ulaşım süresi uzadığında çalışan performansını ve yaşam kalitesini olumsuz etkilediği görülüyor.

ai_location = pd.crosstab(
    remote_df["Work_Location"],
    remote_df["AI_Usage"]
)

ai_location

ai_location.plot(
    kind="bar",
    figsize=(8,5)
)

plt.title("Çalışma Modeli ve Ai Kullanımı İlişkisi")

plt.ylabel("Çalışan Sayısı")

plt.show()
#Remote çalışanların büyük çoğunluğu Ai kullanıyor. On-site çalışanların büyük çoğunluğu Ai kullanmıyor.

"""# AI Kullanımı, Çalışma Modelleri ve Çalışan Verimliliği Analizi

AI araç kullanımı, remote, hybrid ve ofisten çalışma modelleri ile çalışan wellbeing’i (refah/yaşam kalitesi), productivity’si (verimliliği) ve commute (ulaşım) süresi arasındaki ilişkilerin Python tabanlı veri analizi ve görselleştirme yöntemleri ile incelenmesi.
---

# Proje Amacı

Bu projenin amacı:

- çalışma modeli,
- AI araç kullanımı,
- commute (ulaşım) süresi,
- haftalık çalışma saati,
- wellbeing (refah/yaşam kalitesi) seviyesi

gibi değişkenlerin çalışan verimliliği üzerindeki etkilerini analiz etmektir.

---

# Kullanılan Teknolojiler

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

---

# Veri Seti İçeriği

Veri setinde çalışanlara ait:

- yaş,
- çalışma modeli,
- sektör,
- AI araç kullanımı,
- haftalık çalışma süresi,
- productivity (verimlilik) skoru,
- wellbeing (refah/yaşam kalitesi) skoru,
- commute (ulaşım) süresi

gibi bilgiler bulunmaktadır.

---

# Yapılan Analizler

Proje kapsamında:

- Veri temizleme işlemleri yapılmıştır
- Eksik veriler düzenlenmiştir
- Çalışma modeli dağılımları incelenmiştir
- AI kullanım analizleri gerçekleştirilmiştir
- Productivity (verimlilik) ve wellbeing (refah/yaşam kalitesi) ilişkileri analiz edilmiştir
- Korelasyon analizleri yapılmıştır
- Veri görselleştirme işlemleri uygulanmıştır

---

# Önemli Bulgular

## Remote (uzaktan) çalışanlar daha yüksek wellbeing (refah/yaşam kalitesi) seviyesine sahiptir

Analizler sonucunda remote (uzaktan) çalışanların wellbeing (refah/yaşam kalitesi) skorlarının diğer çalışma modellerine göre daha yüksek olduğu gözlemlenmiştir.

---

## Remote çalışanların productivity (verimlilik) seviyeleri daha yüksektir

Remote çalışanların productivity (verimlilik) skorlarının hybrid (hibrit) ve ofisten çalışanlara göre daha yüksek olduğu görülmüştür.

---

## AI araç kullanımı productivity (verimlilik) üzerinde olumlu etki göstermektedir

AI araçları kullanan çalışanların productivity (verimlilik) skorlarının daha yüksek olduğu gözlemlenmiştir.

---

## AI araçları wellbeing (refah/yaşam kalitesi) seviyesini destekleyebilir

AI kullanan çalışanların wellbeing (refah/yaşam kalitesi) skorlarının genel olarak daha yüksek olduğu görülmüştür.

---

## Commute (ulaşım) süresi wellbeing (refah/yaşam kalitesi) üzerinde olumsuz etki oluşturmaktadır

Commute (ulaşım) süresi arttıkça wellbeing (refah/yaşam kalitesi) ve productivity (verimlilik) skorlarının düştüğü gözlemlenmiştir.

Özellikle ofisten çalışanlarda daha düşük wellbeing (refah/yaşam kalitesi) seviyeleri dikkat çekmektedir.

---

## Wellbeing (refah/yaşam kalitesi) ve productivity (verimlilik) arasında güçlü ilişki bulunmaktadır.

Wellbeing (refah/yaşam kalitesi) seviyesi yüksek çalışanların productivity (verimlilik) skorlarının da daha yüksek olduğu görülmüştür.

---

# Genel Sonuç

Bu proje sonuçları:

- remote (uzaktan) çalışma modelinin,
- AI araç kullanımının,
- düşük commute (ulaşım) süresinin

çalışan wellbeing’i (refahı/yaşam kalitesi) ve productivity’si (verimliliği) üzerinde olumlu etkiler oluşturabileceğini göstermektedir.

"""